name: 'dbt_graph_theory'
version: '0.2.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
log-path: "logs"
