integration_tests:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: localhost
      user: ci_user
      password: "ci"
      port: 5432
      dbname: ci_db
      schema: ci_schema
      threads: 2
    bigquery:
      type: bigquery
      method: service-account
      project: james-dtype-test
      dataset: james-dtype-test
      threads: 2
      keyfile: bigquery_secret.json
