integration_tests:
  target: ci_postgres
  outputs:
    ci_postgres:
      type: postgres
      host: localhost
      user: ci_user
      password: "ci"
      port: 5432
      dbname: ci_db
      schema: ci_schema
      threads: 2
    bigquery:
      type: bigquery
      method: service-account
      project: james-dtype-test
      dataset: james-dtype-test
      threads: 2
      keyfile: bigquery_secret.json
    ci_duckdb:
      type: duckdb
      path: 'db/ci_db.duckdb'
