name: CI
defaults:
  run:
    shell: bash
    working-directory: integration_tests
on: [push]
jobs:
  test_lint:
    runs-on: ubuntu-latest
    name: Run Tests
    services:
      postgres:
        image: postgres:14.0-alpine
        env:
          POSTGRES_USER: ci_user
          POSTGRES_DB: ci_db
          POSTGRES_PASSWORD: ci
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Setup python venv
        uses: syphar/restore-virtualenv@v1
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run dbt deps
        run: dbt deps
      - name: Run dbt seed
        run: dbt seed --profiles-dir ci_profiles
      - name: Run dbt models & tests
        run: dbt build -s dbt_graph_theory_integration_tests --profiles-dir ci_profiles
